### ISSUE TITLE
Yuppi を殺すときにディレイを入れて悲鳴をあげさせたい

### ISSUE THREAD

**Issue by hozuki0** [hozuki0/Hinagiku#17]
**どんな機能?**
Banish メッセージの後人間の会話のようなディレイを入れて悲鳴をあげてほしい

**どんな経緯で必要か、何に対してほしいのか**
doseisannの趣味

**Comment by Egliss** [comment]
（0.5秒前後待機）
「ｱｧｯ...」
（2秒前後待機）
「自害下UD」
みたいなの

**Comment by hozuki0** [comment]
簡単に実装する都合上1秒以下の精密制御は放棄してるから必要なら実装しなおす
