### ISSUE TITLE
ダイスロール機能

### ISSUE THREAD

**Issue by Egliss** [hozuki0/Hinagiku#4]
#### どんな機能?
TRPGなどで用いられている **ダイスロール機能** を追加する

以下のような構文を想定
`AdB+C` => B面ダイスをA個振り、その合計値+Cが達成値となる　成否は存在しない
`AdB+C < D`上記に加え、「何が成功か」を条件付けする　<, <=, =, >=, > に対応する
`AdB+C < D 【E】`上記に加え、何に対する判定かを加える　返答にのみ影響する

何かしらprefixを付けた方がいいと思われる（/とか？）
リプライは必要とせず、botの存在する部屋で上記構文を喋った際に起動する

[Input]    `/1d100+1 < 50 【睡眠】`
[Output] `【睡眠】39 < 50 （Success!）`

**出力文に関しては要検討**

A,B,C,Dは半角数字
Eは文字列

---
#### どんな経緯で必要か、何に対してほしいのか
+ 微妙な判断に苦しんだ際に使用　

#### TODO:
- [ ] AdB + CdD　といった構文を許容するかどうか
- [ ] "d"は"D"でも代用可能であって欲しい
- [ ] +Cの演算子は四則演算に対応して欲しい

Edit: 06/10
- [ ] 不正な構文を検知した際の反応

**Comment by hozuki0** [comment]
1d6+3 < 8
という例でやると6面ダイスを1つ振った結果に3を足したものが8を超えていたら成功という認識でいい??
