### ISSUE TITLE
ウルトラマン

### ISSUE THREAD

**Issue by FcAqx** [hozuki0/Hinagiku#5]
**どんな機能?**
金晩に低確率で現れるゲロったー

**どんな経緯で必要か、何に対してほしいのか**
CEDECで現れた謎のウルトラマンが今Discordに蘇る！

**Comment by FcAqx** [comment]
> 
> 
> **どんな機能?**
> 金晩に低確率で現れるゲロったー
> 
> **どんな経緯で必要か、何に対してほしいのか**
> CEDECで現れた謎のウルトラマンが今Discordに蘇る！

**Comment by hozuki0** [comment]
金晩だけじゃ稼働率低いからYuppi☆をお酒に誘うとウルトラマンできるようにします

**Comment by hozuki0** [comment]
#6
